# Generated by Django 3.2.3 on 2021-05-13 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creep', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creep',
            name='gamename',
            field=models.CharField(default='CREEPCRAFT', max_length=50),
        ),
    ]
